build:
	mpicc main.c -o main
run1:
	mpirun -oversubscribe -np 5 main tests/in/input1.txt tests/out/input1.out
run2:
	mpirun -oversubscribe -np 5 main tests/in/input2.txt tests/out/input2.out
run3:
	mpirun -oversubscribe -np 5 main tests/in/input3.txt tests/out/input3.out
run4:
	mpirun -oversubscribe -np 5 main tests/in/input4.txt tests/out/input4.out
run5:
	mpirun -oversubscribe -np 5 main tests/in/input5.txt tests/out/input5.out