build:
	gcc ex1.c -o ex1 -lpthread
	gcc ex2.c -o ex2 -lpthread
	gcc ex3.c -o ex3 -lpthread
	gcc ex4.c -o ex4 -lpthread
	gcc ex5.c -o ex5 -lpthread
	gcc ex6.c -o ex6 -lpthread
clean:
	rm ex1 ex2 ex3 ex4 ex5 ex6
